<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RootNamespace>DecoderBaseline</RootNamespace>
    <AssemblyName>DecoderBaseline</AssemblyName>
    <StartupObject>DecoderBaseline.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\bbc-cassette-loader.csproj" />
    <Reference Include="NAudio.Core">
      <HintPath>..\..\packages\NAudio.Core.2.0.0\lib\netstandard2.0\NAudio.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
